describe('Global Test', () => {
    it('App Title and Summary', () => {
        cy.get('@contentJSON').then((content) => {
            cy.get('[data-testid="generalInfoHeader"]').should('have.text', content.title).and('be.visible')
            cy.get('[data-testid="generalInfoHeaderIntro"]').should('have.text', content.subTitle).and('be.visible')
            cy.get('[data-testid="stepIndicatorStep2"]').click()
            cy.get('[data-testid="filingStatusHeader"]').should('have.text', content.title).and('be.visible')
            cy.get('[data-testid="filingStatusHeaderIntro"]').should('have.text', content.subTitle).and('be.visible')
            cy.get('[data-testid="stepIndicatorStep3"]').click()
            cy.get('[data-testid="agiHeader"]').should('have.text', content.title).and('be.visible')
            cy.get('[data-testid="agiHeaderIntro"]').should('have.text', content.subTitle).and('be.visible')
            cy.get('[data-testid="stepIndicatorStep4"]').click()
            cy.get('[data-testid="qualifyingChildrenHeader"]').should('have.text', content.title).and('be.visible')
            cy.get('[data-testid="qualifyingChildrenHeaderIntro"]').should('have.text', content.subTitle).and('be.visible')
            cy.get('[data-testid="stepIndicatorStep5"]').click()
            cy.get('[data-testid="resultsHeader"]').should('have.text', content.title).and('be.visible')
            cy.get('[data-testid="resultsHeaderIntro"]').should('have.text', content.subTitle).and('be.visible')
        })
    })
})
