Cypress.Commands.add('generalPage', () => {
  cy.get('[data-testid="year-2023"]').click()
  cy.get('[data-testid="citizen-yes"]').click()
  cy.get('[data-testid="validSSN-yes"]').click()
  cy.get('[data-testid="foreignIncome-no"]').click()
  cy.get('[data-testid="claimedAsDependent-no"]').click()
  cy.get('[data-testid="age-2023-input-age-25-64"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="filingStatusTitle"]').should('be.visible')
})
Cypress.Commands.add('filingStatusPage', () => {
  cy.get('[data-testid="year-2023"]').click()
  cy.get('[data-testid="citizen-yes"]').click()
  cy.get('[data-testid="validSSN-yes"]').click()
  cy.get('[data-testid="foreignIncome-no"]').click()
  cy.get('[data-testid="claimedAsDependent-no"]').click()
  cy.get('[data-testid="age-2023-input-under24"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="filingStatusTitle"]').should('be.visible')
  cy.get('[data-testid="fsKnown-yes"]').click()
  cy.get('[data-testid="filingStatus-single"]').click()
  cy.get('[data-testid="numOfDependents-10"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="agiTitle"]').should('be.visible')
})
Cypress.Commands.add('agiPage', () => {
  cy.get('[data-testid="year-2023"]').click()
  cy.get('[data-testid="citizen-yes"]').click()
  cy.get('[data-testid="validSSN-yes"]').click()
  cy.get('[data-testid="foreignIncome-no"]').click()
  cy.get('[data-testid="claimedAsDependent-no"]').click()
  cy.get('[data-testid="age-2023-age-25-64"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="filingStatusTitle"]').should('be.visible')
  cy.get('[data-testid="fsKnown-yes"]').click()
  cy.get('[data-testid="filingStatus-single"]').click()
  cy.get('[data-testid="numOfDependents-10"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="agiTitle"]').should('be.visible')
  cy.get('[data-testid="earnedIncome.wagesFederalWithheld.checked"]').click()
  cy.get('[data-testid="wagesFederalWithheld0-input"]').type('30000')
  cy.get('[data-testid="noUnEarnedIncome"]').click()
  cy.get('[data-testid="noAdjustments"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="qualifyingChildrenTitle"]').should('be.visible')
})
Cypress.Commands.add('agiPageNonArpa', () => {
  cy.get('[data-testid="year-2023"]').click()
  cy.get('[data-testid="citizen-yes"]').click()
  cy.get('[data-testid="validSSN-yes"]').click()
  cy.get('[data-testid="foreignIncome-no"]').click()
  cy.get('[data-testid="claimedAsDependent-no"]').click()
  cy.get('[data-testid="age-2023-age-25-64"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="filingStatusTitle"]').should('be.visible')
  cy.get('[data-testid="fsKnown-yes"]').click()
  cy.get('[data-testid="filingStatus-single"]').click()
  cy.get('[data-testid="numOfDependents-10"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="agiTitle"]').should('be.visible')
  cy.get('[data-testid="earnedIncome.wagesFederalWithheld.checked"]').click()
  cy.get('[data-testid="wagesFederalWithheld0-input"]').type('10000')
  cy.get('[data-testid="noUnEarnedIncome"]').click()
  cy.get('[data-testid="noAdjustments"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="qualifyingChildrenTitle"]').should('be.visible')
})
Cypress.Commands.add('agiPageMFJ', () => {
  cy.get('[data-testid="year-2023"]').click()
  cy.get('[data-testid="citizen-yes"]').click()
  cy.get('[data-testid="validSSN-yes"]').click()
  cy.get('[data-testid="foreignIncome-no"]').click()
  cy.get('[data-testid="claimedAsDependent-no"]').click()
  cy.get('[data-testid="age-2023-input-under24"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="filingStatusTitle"]').should('be.visible')
  cy.get('[data-testid="fsKnown-yes"]').click()
  cy.get('[data-testid="filingStatus-married"]').click() // MFJ
  cy.get('[data-testid="spouseValidSSN-yes"]').click() // spouse ssn
  cy.get('[data-testid="wasSpouseAliveEndOfYear-input-yes"]').click()//spouse alive
  cy.get('[data-testid="spouseAge-input-under24"]').click()//spouse age
  cy.get('[data-testid="numOfDependents-10"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="agiTitle"]').should('be.visible')
  cy.get('[data-testid="earnedIncome.wagesFederalWithheld.checked"]').click()
  cy.get('[data-testid="wagesFederalWithheld0-input"]').type('30000')
  cy.get('[data-testid="noUnEarnedIncome"]').click()
  cy.get('[data-testid="noAdjustments"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="qualifyingChildrenTitle"]').should('be.visible')
})
Cypress.Commands.add('agiPageIncomeEligible', () => {
  cy.get('[data-testid="year-2023"]').click()
  cy.get('[data-testid="citizen-yes"]').click()
  cy.get('[data-testid="validSSN-yes"]').click()
  cy.get('[data-testid="foreignIncome-no"]').click()
  cy.get('[data-testid="claimedAsDependent-no"]').click()
  cy.get('[data-testid="age-2023-input-under24"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="filingStatusTitle"]').should('be.visible')
  cy.get('[data-testid="fsKnown-yes"]').click()
  cy.get('[data-testid="filingStatus-single"]').click()
  cy.get('[data-testid="numOfDependents-10"]').click() 
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="agiTitle"]').should('be.visible')
  cy.get('[data-testid="earnedIncome.wagesFederalWithheld.checked"]').click()
  cy.get('[data-testid="wagesFederalWithheld0-input"]').type('20000') // eligible income
  cy.get('[data-testid="noUnEarnedIncome"]').click()
  cy.get('[data-testid="noAdjustments"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="qualifyingChildrenTitle"]').should('be.visible')
})
Cypress.Commands.add('agiNoDependents', () => {
  cy.get('[data-testid="year-2023"]').click()
  cy.get('[data-testid="citizen-yes"]').click()
  cy.get('[data-testid="validSSN-yes"]').click()
  cy.get('[data-testid="foreignIncome-no"]').click()
  cy.get('[data-testid="claimedAsDependent-input-no"]').click()
  cy.get('[data-testid="age-2023-input-age-25-64"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="filingStatusTitle"]').should('be.visible')
  cy.get('[data-testid="fsKnown-yes"]').click()
  cy.get('[data-testid="filingStatus-single"]').click()
  cy.get('[data-testid="numOfDependents-input-"]').click()
  cy.get('[data-testid="us50Percent-label"]').click()
  cy.get('[data-testid="us50Percent-yes"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="agiTitle"]').should('be.visible')
  cy.get('[data-testid="earnedIncome.wagesFederalWithheld.checked"]').click()
  cy.get('[data-testid="wagesFederalWithheld0-input"]').type('17639')
  cy.get('[data-testid="noUnEarnedIncome"]').click()
  cy.get('[data-testid="noAdjustments"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="qualifyingChildrenTitle"]').should('be.visible')
})
Cypress.Commands.add('qualifyingChildrenPage', () => {
  cy.get('[data-testid="year-2023"]').click()
  cy.get('[data-testid="citizen-yes"]').click()
  cy.get('[data-testid="validSSN-yes"]').click()
  cy.get('[data-testid="foreignIncome-no"]').click()
  cy.get('[data-testid="claimedAsDependent-no"]').click()
  cy.get('[data-testid="age-2023-input-age-25-64"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="filingStatusTitle"]').should('be.visible')
  cy.get('[data-testid="fsKnown-yes"]').click()
  cy.get('[data-testid="filingStatus-married"]').click()
  cy.get('[data-testid="spouseValidSSN-yes"]').click()
  cy.get('[data-testid="numOfDependents-10"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="agiTitle"]').should('be.visible')

  cy.get('[data-testid="earnedIncome.wagesFederalWithheld.checked"]').click()
  cy.get('[data-testid="wagesFederalWithheld0-input"]').type('50000').should('have.value', '$50,000')
  cy.get('[data-testid="addAnother-wagesFederalWithheld"]').click()
  cy.get('[data-testid="wagesFederalWithheld1-input"]').type('1').should('have.value', '$1')

  cy.get('[data-testid="taxDeferredRetirementLabel"]').click()
  cy.get('[data-testid="taxDeferredRetirement0-input"]').type('1').should('have.value', '$1')
  
  cy.get('[data-testid="cafeteriaLabel"]').click()
  cy.get('[data-testid="cafeteria0-input"]').type('2').should('have.value', '$2')
  
  cy.get('[data-testid="healthInsuranceLabel"]').click()
  cy.get('[data-testid="healthInsurance0-input"]').type('3').should('have.value', '$3')
      
  cy.get('[data-testid="federalIncomeNotWithheldLabel"]').click()
  cy.get('[data-testid="federalIncomeNotWithheld0-input"]').type('4').should('have.value', '$4')
  
  cy.get('[data-testid="selfEmploymentPaidFINWLabel"]').click()
  cy.get('[data-testid="selfEmploymentPaidFINW0-input"]').type('5').should('have.value', '$5')
  
  cy.get('[data-testid="sepSimpleFINWLabel"]').click()
  cy.get('[data-testid="sepSimpleFINW0-input"]').type('19').should('have.value', '$19')
  
  cy.get('[data-testid="selfEmploymentInsuranceFINWLabel"]').click()
  cy.get('[data-testid="selfEmploymentInsuranceFINW0-input"]').type('20').should('have.value', '$20')
  
  cy.get('[data-testid="selfEmploymentExpensesFINWLabel"]').click()
  cy.get('[data-testid="selfEmploymentExpensesFINW0-input"]').type('6').should('have.value', '$6')
  
  cy.get('[data-testid="selfEmploymentGrossLabel"]').click()
  cy.get('[data-testid="selfEmploymentGross0-input"]').type('7').should('have.value', '$7')
  
  cy.get('[data-testid="selfEmploymentPaidSEGLabel"]').click()
  cy.get('[data-testid="selfEmploymentPaidSEG0-input"]').type('8').should('have.value', '$8')
  
  cy.get('[data-testid="sepSimpleSEGLabel"]').click()
  cy.get('[data-testid="sepSimpleSEG0-input"]').type('21').should('have.value', '$21')
  
  cy.get('[data-testid="selfEmploymentInsuranceSEGLabel"]').click()
  cy.get('[data-testid="selfEmploymentInsuranceSEG0-input"]').type('22').should('have.value', '$22')
  
  cy.get('[data-testid="selfEmploymentExpensesSEGLabel"]').click()
  cy.get('[data-testid="selfEmploymentExpensesSEG0-input"]').type('9').should('have.value', '$9')
  
  cy.get('[data-testid="disabilityRetirementLabel"]').click()
  cy.get('[data-testid="disabilityRetirement0-input"]').type('10').should('have.value', '$10')
  
  cy.get('[data-testid="foreignEarnedIncomeLabel"]').click()
  cy.get('[data-testid="foreignEarnedIncome0-input"]').type('11').should('have.value', '$11')
  
  cy.get('[data-testid="prisonIncomeLabel"]').click()
  cy.get('[data-testid="prisonIncome0-input"]').type('12').should('have.value', '$12')
  
  cy.get('[data-testid="pensionLabel"]').click()
  cy.get('[data-testid="pension0-input"]').type('13').should('have.value', '$13')
  
  cy.get('[data-testid="unemploymentInsuranceLabel"]').click()
  cy.get('[data-testid="unemploymentInsurance0-input"]').type('14').should('have.value', '$14')
  
  cy.get('[data-testid="socialSecurityRailroadLabel"]').click()
  cy.get('[data-testid="socialSecurityRailroad0-input"]').type('15').should('have.value', '$15')
  
  cy.get('[data-testid="scholarshipLabel"]').click()
  cy.get('[data-testid="scholarship0-input"]').type('16').should('have.value', '$16')
  
  cy.get('[data-testid="investmentsLabel"]').click()
  cy.get('[data-testid="investments0-input"]').type('17').should('have.value', '$17')
  
  cy.get('[data-testid="unearnedOtherLabel"]').click()
  cy.get('[data-testid="unearnedOther0-input"]').type('18').should('have.value', '$18')
  
  cy.get('[data-testid="studentLoanLabel"]').click()
  cy.get('[data-testid="studentLoan0-input"]').type('23').should('have.value', '$23')
  
  cy.get('[data-testid="educatorLabel"]').click()
  cy.get('[data-testid="educator0-input"]').type('24').should('have.value', '$24')
  
  cy.get('[data-testid="iraLabel"]').click()
  cy.get('[data-testid="ira0-input"]').type('25').should('have.value', '$25')
  
  cy.get('[data-testid="hsaLabel"]').click()
  cy.get('[data-testid="hsa0-input"]').type('26').should('have.value', '$26')
  
  cy.get('[data-testid="movingLabel"]').click()
  cy.get('[data-testid="moving0-input"]').type('27').should('have.value', '$27')
  
  cy.get('[data-testid="alimonyLabel"]').click()
  cy.get('[data-testid="alimony0-input"]').type('28').should('have.value', '$28')
  
  cy.get('[data-testid="earlyWithdrawalPenaltyLabel"]').click()
  cy.get('[data-testid="earlyWithdrawalPenalty0-input"]').type('29').should('have.value', '$29')
  
  cy.get('[data-testid="businessLabel"]').click()
  cy.get('[data-testid="business0-input"]').type('30').should('have.value', '$30')
  
  cy.get('[data-testid="otherAdjustmentsLabel"]').click()
  cy.get('[data-testid="otherAdjustments0-input"]').type('31').should('have.value', '$31')

  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="children.0.live51Pct-yes"]').click()
  cy.get('[data-testid="children.0.claimOther-no"]').click()
  cy.get('[data-testid="children.0.fileJoint-no"]').click()
  cy.get('[data-testid="children.0.permanentlyDisabled-no"]').click()
  cy.get('[data-testid="children.0.relationship-qualifyingRelationship1"]').click()
  cy.get('[data-testid="children.0.age-age-Under18"]').click()
  cy.get('[data-testid="children.0.validSSN-yes"]').click()
  cy.get('[id="child2-trigger"]').click()
  cy.get('[data-testid="children.1.live51Pct-yes"]').click()
  cy.get('[data-testid="children.1.claimOther-no"]').click()
  cy.get('[data-testid="children.1.fileJoint-no"]').click()
  cy.get('[data-testid="children.1.permanentlyDisabled-no"]').click()
  cy.get('[data-testid="children.1.relationship-qualifyingRelationship1"]').click()
  cy.get('[data-testid="children.1.age-age-Under18"]').click()
  cy.get('[data-testid="children.1.validSSN-yes"]').click()
  cy.get('[id="child3-trigger"]').click()
  cy.get('[data-testid="children.2.live51Pct-yes"]').click()
  cy.get('[data-testid="children.2.claimOther-no"]').click()
  cy.get('[data-testid="children.2.fileJoint-no"]').click()
  cy.get('[data-testid="children.2.permanentlyDisabled-no"]').click()
  cy.get('[data-testid="children.2.relationship-qualifyingRelationship1"]').click()
  cy.get('[data-testid="children.2.age-age-Under18"]').click()
  cy.get('[data-testid="children.2.validSSN-yes"]').click()
  cy.get('[data-testid="nextButton"]').click()
  cy.get('[data-testid="resultsTitle"]').should('be.visible')
})