describe('Scenarios Script', () => {
    it('Scenario 1 - Suzie MFJ', () => {
        cy.get('@contentJSON').then((content) => {
            cy.get('[data-testid="year-2021"]').click()
            cy.get('[data-testid="citizen-yes"]').click()
            cy.get('[data-testid="validSSN-yes"]').click()
            cy.get('[data-testid="foreignIncome-no"]').click()
            cy.get('[data-testid="claimedAsDependent-no"]').click()
            cy.get('[data-testid="age-2021-18"]').click()
            cy.get('[data-testid="qualifiedHomelessYouth-no"]').click()
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="fsKnown-yes"]').click()
            cy.get('[data-testid="filingStatus-married"]').click()
            cy.get('[data-testid="spouseValidSSN-yes"]').click()
            cy.get('[data-testid="wasSpouseAliveEndOfYear-yes"]').click()
            cy.get('[data-testid="spouseAge-18"]').click()
            cy.get('[data-testid="spouseQualifiedHomelessYouth-yes"]').click()
            cy.get('[data-testid="numOfDependents-"]').click()//None
            cy.get('[data-testid="us50Percent-label"]').click()
            cy.get('[data-testid="us50Percent-yes"]').click()
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="earnedIncome.wagesFederalWithheld.checked"]').click()
            cy.get('[data-testid="wagesFederalWithheld0-input"]').type('25225').should('have.value', '$25,225')
            cy.get('[data-testid="foreignEarnedIncomeLabel"]').click()
            cy.get('[data-testid="foreignEarnedIncome0-input"]').type('1000').should('have.value', '$1,000')
            cy.get('[data-testid="unearnedOtherLabel"]').click()
            cy.get('[data-testid="unearnedOther0-input"]').type('1000').should('have.value', '$1,000')
            cy.get('[data-testid="otherAdjustmentsLabel"]').click()
            cy.get('[data-testid="otherAdjustments0-input"]').type('1000').should('have.value', '$1,000')
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="noQCParagraph"]').should('be.visible')
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="resultsIntro-p1"]').contains('$177')
        })
    })
    it('Scenario 2 - Cindy MFJ', () => {
        cy.get('@contentJSON').then((content) => {
            cy.get('[data-testid="year-2021"]').click()
            cy.get('[data-testid="citizen-yes"]').click()
            cy.get('[data-testid="validSSN-yes"]').click()
            cy.get('[data-testid="foreignIncome-no"]').click()
            cy.get('[data-testid="claimedAsDependent-no"]').click()
            cy.get('[data-testid="age-2021-17under"]').click()
            cy.get('[data-testid="nextButton"]').click()
            
            cy.get('[data-testid="fsKnown-no"]').click()
            cy.get('[data-testid="maritalStatus-widow"]').click()
            cy.get('[data-testid="spousesPassing-lastYear"]').click()
            cy.get('[data-testid="intendJointReturnDeceased-yes"]').click()
            cy.get('[data-testid="deceasedSpouseValidSSN-yes"]').click()
            cy.get('[data-testid="deceasedSpouseAge-19-23"]').click()
            cy.get('[data-testid="deceasedSpouseQualifiedHomelessYouth-no"]').click()
            cy.get('[data-testid="deceasedSpouseStudent-yes"]').click()
            cy.get('[data-testid="numOfDependents-10"]').click() //1
            cy.get('[data-testid="nextButton"]').click()
            cy.get('[data-testid="agiTitle"]').should('be.visible')

            cy.get('[data-testid="earnedIncome.wagesFederalWithheld.checked"]').click()
            cy.get('[data-testid="wagesFederalWithheld0-input"]').type('41025').should('have.value', '$41,025')
            cy.get('[data-testid="unemploymentInsuranceLabel"]').click()
            cy.get('[data-testid="unemploymentInsurance0-input"]').type('1000').should('have.value', '$1,000')
            cy.get('[data-testid="businessLabel"]').click()
            cy.get('[data-testid="business0-input"]').type('3000').should('have.value', '$3,000')
            cy.get('[data-testid="otherAdjustmentsLabel"]').click()
            cy.get('[data-testid="otherAdjustments0-input"]').type('31').should('have.value', '$31')

            cy.get('[data-testid="nextButton"]').click()
            cy.get('[data-testid="children.0.live51Pct-yes"]').click()
            cy.get('[data-testid="children.0.claimOther-yes"]').click()
            cy.get('[data-testid="children.0.claimOtherConfirm-yes"]').click()
            cy.get('[data-testid="children.0.fileJoint-yes"]').click()
            cy.get('[data-testid="children.0.fileJointConfirm-yes"]').click()
            cy.get('[data-testid="children.0.permanentlyDisabled-no"]').click()
            cy.get('[data-testid="children.0.relationship-qualifyingRelationship1"]').click()
            cy.get('[data-testid="children.0.age-age-Under18"]').click()
            cy.get('[data-testid="children.0.validSSN-yes"]').click()

            cy.get('[data-testid="nextButton"]').click()
            cy.get('[data-testid="resultsIntro-p1"]').contains('$1,133')
        })
    })
    it('Scenario 3 - Tom MFS', () => {
        cy.get('@contentJSON').then((content) => {
            cy.get('[data-testid="year-2021"]').click()
            cy.get('[data-testid="citizen-yes"]').click()
            cy.get('[data-testid="validSSN-yes"]').click()
            cy.get('[data-testid="foreignIncome-no"]').click()
            cy.get('[data-testid="claimedAsDependent-no"]').click()
            cy.get('[data-testid="age-2021-24over"]').click()
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="fsKnown-yes"]').click()
            cy.get('[data-testid="filingStatus-married-Separate"]').click()
            cy.get('[data-testid="liveApartFromSpouse-yes"]').click()
            cy.get('[data-testid="mfsLegalDoc-yes"]').click()
            cy.get('[data-testid="numOfDependents-10"]').click() //5
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="disabilityRetirementLabel"]').click()
            cy.get('[data-testid="disabilityRetirement0-input"]').type('35000').should('have.value', '$35,000')
            cy.get('[data-testid="pensionLabel"]').click()
            cy.get('[data-testid="pension0-input"]').type('1000').should('have.value', '$1,000')
            cy.get('[data-testid="investmentsLabel"]').click()
            cy.get('[data-testid="investments0-input"]').type('1000').should('have.value', '$1,000')
            cy.get('[data-testid="unearnedOtherLabel"]').click()
            cy.get('[data-testid="unearnedOther0-input"]').type('4000').should('have.value', '$4,000')
            cy.get('[data-testid="educatorLabel"]').click()
            cy.get('[data-testid="educator0-input"]').type('300').should('have.value', '$300')
            cy.get('[data-testid="iraLabel"]').click()
            cy.get('[data-testid="ira0-input"]').type('5000').should('have.value', '$5,000')
            cy.get('[data-testid="earlyWithdrawalPenaltyLabel"]').click()
            cy.get('[data-testid="earlyWithdrawalPenalty0-input"]').type('1000').should('have.value', '$1,000')
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="children.0.live51Pct-yes"]').click()
            cy.get('[data-testid="children.0.claimOther-no"]').click()
            cy.get('[data-testid="children.0.fileJoint-no"]').click()
            cy.get('[data-testid="children.0.permanentlyDisabled-no"]').click()
            cy.get('[data-testid="children.0.relationship-qualifyingRelationship3"]').click()
            cy.get('[data-testid="children.0.age-age-19-23"]').click()
            cy.get('[data-testid="children.0.student-yes"]').click()
            cy.get('[data-testid="children.0.validSSN-no"]').click()

            cy.get('[id="child2-trigger"]').click()
            cy.get('[data-testid="children.1.live51Pct-yes"]').click()
            cy.get('[data-testid="children.1.claimOther-no"]').click()
            cy.get('[data-testid="children.1.fileJoint-no"]').click()
            cy.get('[data-testid="children.1.permanentlyDisabled-no"]').click()
            cy.get('[data-testid="children.1.relationship-qualifyingRelationship1"]').click()
            cy.get('[data-testid="children.1.age-age-19-23"]').click()
            cy.get('[data-testid="children.1.student-no"]').click()

            cy.get('[id="child3-trigger"]').click()
            cy.get('[data-testid="children.2.live51Pct-yes"]').click()
            cy.get('[data-testid="children.2.claimOther-no"]').click()
            cy.get('[data-testid="children.2.fileJoint-no"]').click()
            cy.get('[data-testid="children.2.permanentlyDisabled-no"]').click()
            cy.get('[data-testid="children.2.relationship-qualifyingRelationship1"]').click()
            cy.get('[data-testid="children.2.age-age-19-23"]').click()
            cy.get('[data-testid="children.2.student-yes"]').click()
            cy.get('[data-testid="children.2.validSSN-yes"]').click()

            cy.get('[id="child4-trigger"]').click()            
            cy.get('[data-testid="children.3.live51Pct-yes"]').click()
            cy.get('[data-testid="children.3.claimOther-no"]').click()
            cy.get('[data-testid="children.3.fileJoint-no"]').click()
            cy.get('[data-testid="children.3.permanentlyDisabled-yes"]').click()
            cy.get('[data-testid="children.3.relationship-qualifyingRelationship2"]').click()
            cy.get('[data-testid="children.3.validSSN-yes"]').click()
            
            cy.get('[id="child5-trigger"]').click() 
            cy.get('[data-testid="children.4.live51Pct-yes"]').click()
            cy.get('[data-testid="children.4.claimOther-no"]').click()
            cy.get('[data-testid="children.4.fileJoint-no"]').click()
            cy.get('[data-testid="children.4.permanentlyDisabled-no"]').click()
            cy.get('[data-testid="children.4.relationship-qualifyingRelationship2"]').click()
            cy.get('[data-testid="children.4.age-age-Under18"]').click()
            cy.get('[data-testid="children.4.validSSN-yes"]').click()

            cy.get('[data-testid="nextButton"]').click()
            cy.get('[data-testid="resultsIntro-p1"]').contains('$3,463')
        })
    })
    it('Scenario 4 - Bonnie Single', () => {
        cy.get('@contentJSON').then((content) => {
            cy.get('[data-testid="year-2021"]').click()
            cy.get('[data-testid="citizen-yes"]').click()
            cy.get('[data-testid="validSSN-yes"]').click()
            cy.get('[data-testid="foreignIncome-no"]').click()
            cy.get('[data-testid="claimedAsDependent-no"]').click()
            cy.get('[data-testid="age-2021-18"]').click()
            cy.get('[data-testid="qualifiedHomelessYouth-yes"]').click()
            cy.get('[data-testid="nextButton"]').click()
            
            cy.get('[data-testid="fsKnown-yes"]').click()
            cy.get('[data-testid="filingStatus-single"]').click()
            cy.get('[data-testid="numOfDependents-"]').click() //None
            cy.get('[data-testid="us50Percent-label"]').click()
            cy.get('[data-testid="us50Percent-yes"]').click()
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="federalIncomeNotWithheldLabel"]').click()
            cy.get('[data-testid="federalIncomeNotWithheld0-input"]').type('20000').should('have.value', '$20,000')
            cy.get('[data-testid="selfEmploymentPaidFINWLabel"]').click()
            cy.get('[data-testid="selfEmploymentPaidFINW0-input"]').type('2425').should('have.value', '$2,425')
            cy.get('[data-testid="sepSimpleFINWLabel"]').click()
            cy.get('[data-testid="sepSimpleFINW0-input"]').type('2500').should('have.value', '$2,500')
            cy.get('[data-testid="selfEmploymentInsuranceFINWLabel"]').click()
            cy.get('[data-testid="selfEmploymentInsuranceFINW0-input"]').type('2500').should('have.value', '$2,500')
            cy.get('[data-testid="selfEmploymentExpensesFINWLabel"]').click()
            cy.get('[data-testid="selfEmploymentExpensesFINW0-input"]').type('1000').should('have.value', '$1,000')
            cy.get('[data-testid="unearnedOtherLabel"]').click()
            cy.get('[data-testid="unearnedOther0-input"]').type('11000').should('have.value', '$11,000')
            cy.get('[data-testid="studentLoanLabel"]').click()
            cy.get('[data-testid="studentLoan0-input"]').type('2500').should('have.value', '$2,500')
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="noQCParagraph"]').should('be.visible')
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="resultsIntro-p1"]').contains('$209')
        })
    })
    it('Scenario 5 - Steve Single', () => {
        cy.get('@contentJSON').then((content) => {
            cy.get('[data-testid="year-2021"]').click()
            cy.get('[data-testid="citizen-yes"]').click()
            cy.get('[data-testid="validSSN-yes"]').click()
            cy.get('[data-testid="foreignIncome-no"]').click()
            cy.get('[data-testid="claimedAsDependent-no"]').click()
            cy.get('[data-testid="age-2021-19-23"]').click()
            cy.get('[data-testid="qualifiedHomelessYouth-no"]').click()
            cy.get('[data-testid="student-no"]').click()
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="fsKnown-no"]').click()
            cy.get('[data-testid="maritalStatus-divorced"]').click()
            cy.get('[data-testid="houseUpkeep3-none"]').click()
            cy.get('[data-testid="numOfDependents-10"]').click() //3
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="selfEmploymentGrossLabel"]').click()
            cy.get('[data-testid="selfEmploymentGross0-input"]').type('40000').should('have.value', '$40,000')
            cy.get('[data-testid="selfEmploymentPaidSEGLabel"]').click()
            cy.get('[data-testid="selfEmploymentPaidSEG0-input"]').type('15000').should('have.value', '$15,000')
            cy.get('[data-testid="sepSimpleSEGLabel"]').click()
            cy.get('[data-testid="sepSimpleSEG0-input"]').type('15000').should('have.value', '$15,000')
            cy.get('[data-testid="selfEmploymentInsuranceSEGLabel"]').click()
            cy.get('[data-testid="selfEmploymentInsuranceSEG0-input"]').type('15000').should('have.value', '$15,000')
            cy.get('[data-testid="selfEmploymentExpensesSEGLabel"]').click()
            cy.get('[data-testid="selfEmploymentExpensesSEG0-input"]').type('5000').should('have.value', '$5,000')
            cy.get('[data-testid="pensionLabel"]').click()
            cy.get('[data-testid="pension0-input"]').type('20000').should('have.value', '$20,000')
            cy.get('[data-testid="unemploymentInsuranceLabel"]').click()
            cy.get('[data-testid="unemploymentInsurance0-input"]').type('20000').should('have.value', '$20,000')
            cy.get('[data-testid="socialSecurityRailroadLabel"]').click()
            cy.get('[data-testid="socialSecurityRailroad0-input"]').type('20000').should('have.value', '$20,000')
            cy.get('[data-testid="unearnedOtherLabel"]').click()
            cy.get('[data-testid="unearnedOther0-input"]').type('10725').should('have.value', '$10,725')
            cy.get('[data-testid="movingLabel"]').click()
            cy.get('[data-testid="moving0-input"]').type('10000').should('have.value', '$10,000')
            cy.get('[data-testid="alimonyLabel"]').click()
            cy.get('[data-testid="alimony0-input"]').type('5000').should('have.value', '$5,000')
            cy.get('[data-testid="businessLabel"]').click()
            cy.get('[data-testid="business0-input"]').type('1000').should('have.value', '$1,000')
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="children.0.live51Pct-yes"]').click()
            cy.get('[data-testid="children.0.claimOther-no"]').click()
            cy.get('[data-testid="children.0.fileJoint-yes"]').click()
            cy.get('[data-testid="children.0.fileJointConfirm-yes"]').click()
            cy.get('[data-testid="children.0.permanentlyDisabled-no"]').click()
            cy.get('[data-testid="children.0.relationship-other"]').click()
            
            cy.get('[id="child2-trigger"]').click() 
            cy.get('[data-testid="children.1.live51Pct-yes"]').click()
            cy.get('[data-testid="children.1.claimOther-no"]').click()
            cy.get('[data-testid="children.1.fileJoint-no"]').click()
            cy.get('[data-testid="children.1.permanentlyDisabled-no"]').click()
            cy.get('[data-testid="children.1.relationship-qualifyingRelationship1"]').click()
            cy.get('[data-testid="children.1.age-age-Under18"]').click()
            cy.get('[data-testid="children.1.validSSN-yes"]').click()
            
            cy.get('[id="child3-trigger"]').click() 
            cy.get('[data-testid="children.2.live51Pct-yes"]').click()
            cy.get('[data-testid="children.2.claimOther-no"]').click()
            cy.get('[data-testid="children.2.fileJoint-no"]').click()
            cy.get('[data-testid="children.2.permanentlyDisabled-no"]').click()
            cy.get('[data-testid="children.2.relationship-qualifyingRelationship1"]').click()
            cy.get('[data-testid="children.2.age-age-Under18"]').click()
            cy.get('[data-testid="children.2.validSSN-yes"]').click()
            
            cy.get('[data-testid="nextButton"]').click()
            cy.get('[data-testid="resultsIntro-p1"]').contains('$672')
        })
    })
    it('Scenario 6 - Jen HOH', () => {
        cy.get('@contentJSON').then((content) => {
            cy.get('[data-testid="year-2021"]').click()
            cy.get('[data-testid="citizen-yes"]').click()
            cy.get('[data-testid="validSSN-yes"]').click()
            cy.get('[data-testid="foreignIncome-no"]').click()
            cy.get('[data-testid="claimedAsDependent-no"]').click()
            cy.get('[data-testid="age-2021-19-23"]').click()
            cy.get('[data-testid="qualifiedHomelessYouth-no"]').click()
            cy.get('[data-testid="student-yes"]').click()
            cy.get('[data-testid="nextButton"]').click()
            
            cy.get('[data-testid="fsKnown-no"]').click()
            cy.get('[data-testid="maritalStatus-neverMarried"]').click()
            cy.get('[data-testid="houseUpkeep3-parent"]').click()
            cy.get('[data-testid="numOfDependents-10"]').click() //3
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="earnedIncome.wagesFederalWithheld.checked"]').click()
            cy.get('[data-testid="wagesFederalWithheld0-input"]').type('14925').should('have.value', '$14,925')
            cy.get('[data-testid="foreignEarnedIncomeLabel"]').click()
            cy.get('[data-testid="foreignEarnedIncome0-input"]').type('5000').should('have.value', '$5,000')
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="children.0.live51Pct-yes"]').click()
            cy.get('[data-testid="children.0.claimOther-no"]').click()
            cy.get('[data-testid="children.0.fileJoint-yes"]').click()
            cy.get('[data-testid="children.0.fileJointConfirm-yes"]').click()
            cy.get('[data-testid="children.0.permanentlyDisabled-yes"]').click()
            cy.get('[data-testid="children.0.relationship-qualifyingRelationship1"]').click()
            cy.get('[data-testid="children.0.validSSN-yes"]').click()

            cy.get('[id="child2-trigger"]').click() 
            cy.get('[data-testid="children.1.live51Pct-yes"]').click()
            cy.get('[data-testid="children.1.claimOther-yes"]').click()
            cy.get('[data-testid="children.1.claimOtherConfirm-yes"]').click()
            cy.get('[data-testid="children.1.fileJoint-yes"]').click()
            cy.get('[data-testid="children.1.fileJointConfirm-yes"]').click()
            cy.get('[data-testid="children.1.permanentlyDisabled-no"]').click()
            cy.get('[data-testid="children.1.relationship-qualifyingRelationship1"]').click()
            cy.get('[data-testid="children.1.age-age-Under18"]').click()
            cy.get('[data-testid="children.1.validSSN-yes"]').click()

            cy.get('[id="child3-trigger"]').click() 
            cy.get('[data-testid="children.2.live51Pct-yes"]').click()
            cy.get('[data-testid="children.2.claimOther-no"]').click()
            cy.get('[data-testid="children.2.fileJoint-no"]').click()
            cy.get('[data-testid="children.2.permanentlyDisabled-yes"]').click()
            cy.get('[data-testid="children.2.relationship-qualifyingRelationship1"]').click()
            cy.get('[data-testid="children.2.validSSN-yes"]').click()
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="resultsIntro-p1"]').contains('$6,643')
        })
    })
    it('Scenario 7 - Mike HOH', () => {
        cy.get('@contentJSON').then((content) => {
            cy.get('[data-testid="year-2021"]').click()
            cy.get('[data-testid="citizen-yes"]').click()
            cy.get('[data-testid="validSSN-yes"]').click()
            cy.get('[data-testid="foreignIncome-no"]').click()
            cy.get('[data-testid="claimedAsDependent-no"]').click()
            cy.get('[data-testid="age-2021-18"]').click()
            cy.get('[data-testid="qualifiedHomelessYouth-no"]').click()
            cy.get('[data-testid="nextButton"]').click()
            
            cy.get('[data-testid="fsKnown-no"]').click()
            cy.get('[data-testid="maritalStatus-married"]').click()
            cy.get('[data-testid="fileJointReturn-no"]').click()
            //Live with spouse helptip
            cy.get('[data-testid="liveWithSpouseHelpTip"]').click()
            cy.get('[data-testid="liveWithSpouseHelpTipHeading1"]').should('have.text', content.toolTip.liveWithSpouseToolTipHeading).and('be.visible')
            cy.get('[data-testid="liveWithSpouseHelpTipParagraph1"]').should('have.text', content.toolTip.liveWithSpouseToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="liveWithSpouseHelpTipList0"]').should('have.text', content.toolTip.liveWithSpouseToolTipList0).and('be.visible')
            cy.get('[data-testid="liveWithSpouseHelpTipList1"]').should('have.text', content.toolTip.liveWithSpouseToolTipList1).and('be.visible')
            cy.get('[data-testid="liveWithSpouseHelpTipList2"]').should('have.text', content.toolTip.liveWithSpouseToolTipList2).and('be.visible')
            cy.get('[data-testid="liveWithSpouseHelpTipList3"]').should('have.text', content.toolTip.liveWithSpouseToolTipList3).and('be.visible')
            cy.get('[data-testid="liveWithSpouseHelpTipList4"]').should('have.text', content.toolTip.liveWithSpouseToolTipList4).and('be.visible')
            cy.get('[data-testid="liveWithSpouseHelpTipParagraph2"]').should('have.text', content.toolTip.liveWithSpouseToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="liveWithSpouseHelpTip"]').click()
            cy.get('[data-testid="liveWithSpouseHelpTipHeading1"]').should('be.not.visible')
            cy.get('[data-testid="liveWithSpouse-no"]').click()
            cy.get('[data-testid="houseUpkeep1-yes"]').click()
            cy.get('[data-testid="numOfDependents-10"]').click() //4
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="federalIncomeNotWithheldLabel"]').click()
            cy.get('[data-testid="federalIncomeNotWithheld0-input"]').type('10000').should('have.value', '$10,000')
            cy.get('[data-testid="selfEmploymentGrossLabel"]').click()
            cy.get('[data-testid="selfEmploymentGross0-input"]').type('20000').should('have.value', '$20,000')
            cy.get('[data-testid="prisonIncomeLabel"]').click()
            cy.get('[data-testid="prisonIncome0-input"]').type('5000').should('have.value', '$5,000')
            cy.get('[data-testid="scholarshipLabel"]').click()
            cy.get('[data-testid="scholarship0-input"]').type('2025').should('have.value', '$2,025')
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="children.0.live51Pct-yes"]').click()
            cy.get('[data-testid="children.0.claimOther-no"]').click()
            cy.get('[data-testid="children.0.fileJoint-yes"]').click()
            cy.get('[data-testid="children.0.fileJointConfirm-yes"]').click()
            cy.get('[data-testid="children.0.permanentlyDisabled-yes"]').click()
            cy.get('[data-testid="children.0.relationship-other"]').click()
            
            cy.get('[id="child2-trigger"]').click() 
            cy.get('[data-testid="children.1.live51Pct-yes"]').click()
            cy.get('[data-testid="children.1.claimOther-no"]').click()
            cy.get('[data-testid="children.1.fileJoint-no"]').click()
            cy.get('[data-testid="children.1.permanentlyDisabled-no"]').click()
            cy.get('[data-testid="children.1.relationship-qualifyingRelationship1"]').click()
            cy.get('[data-testid="children.1.age-age-Under18"]').click()
            cy.get('[data-testid="children.1.younger-no"]').click()

            cy.get('[id="child3-trigger"]').click() 
            cy.get('[data-testid="children.2.live51Pct-yes"]').click()
            cy.get('[data-testid="children.2.claimOther-no"]').click()
            cy.get('[data-testid="children.2.fileJoint-no"]').click()
            cy.get('[data-testid="children.2.permanentlyDisabled-no"]').click()
            cy.get('[data-testid="children.2.relationship-qualifyingRelationship1"]').click()
            cy.get('[data-testid="children.2.age-age-Under18"]').click()
            cy.get('[data-testid="children.2.younger-yes"]').click()
            cy.get('[data-testid="children.2.validSSN-yes"]').click()

            cy.get('[id="child4-trigger"]').click() 
            cy.get('[data-testid="children.3.live51Pct-yes"]').click()
            cy.get('[data-testid="children.3.claimOther-no"]').click()
            cy.get('[data-testid="children.3.fileJoint-no"]').click()
            cy.get('[data-testid="children.3.permanentlyDisabled-no"]').click()
            cy.get('[data-testid="children.3.relationship-qualifyingRelationship2"]').click()
            cy.get('[data-testid="children.3.age-age-Over24"]').click()
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="resultsIntro-p1"]').contains('$821')
        })
    })
    it('Scenario 8 - Fred MFJ', () => {
        cy.get('@contentJSON').then((content) => {
            cy.get('[data-testid="year-2021"]').click()
            cy.get('[data-testid="citizen-yes"]').click()
            cy.get('[data-testid="validSSN-yes"]').click()
            cy.get('[data-testid="foreignIncome-no"]').click()
            cy.get('[data-testid="claimedAsDependent-no"]').click()
            cy.get('[data-testid="age-2021-19-23"]').click()
            cy.get('[data-testid="qualifiedHomelessYouth-no"]').click()
            cy.get('[data-testid="student-yes"]').click()
            cy.get('[data-testid="nextButton"]').click()
            
            cy.get('[data-testid="fsKnown-no"]').click()
            cy.get('[data-testid="maritalStatus-widow"]').click()
            cy.get('[data-testid="spousesPassing-lastYear"]').click()
            cy.get('[data-testid="intendJointReturnDeceased-yes"]').click()
            cy.get('[data-testid="deceasedSpouseValidSSN-yes"]').click()
            cy.get('[data-testid="deceasedSpouseAge-19-23"]').click()
            cy.get('[data-testid="deceasedSpouseQualifiedHomelessYouth-no"]').click()
            cy.get('[data-testid="deceasedSpouseStudent-no"]').click()
            cy.get('[data-testid="numOfDependents-10"]').click() //2
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="earnedIncome.wagesFederalWithheld.checked"]').click()
            cy.get('[data-testid="wagesFederalWithheld0-input"]').type('22379').should('have.value', '$22,379')
            cy.get('[data-testid="socialSecurityRailroadLabel"]').click()
            cy.get('[data-testid="socialSecurityRailroad0-input"]').type('6000').should('have.value', '$6,000')
            cy.get('[data-testid="otherAdjustmentsLabel"]').click()
            cy.get('[data-testid="otherAdjustments0-input"]').type('1000').should('have.value', '$1,000')
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="children.0.live51Pct-no"]').click()

            cy.get('[id="child2-trigger"]').click() 
            cy.get('[data-testid="children.1.live51Pct-yes"]').click()
            cy.get('[data-testid="children.1.claimOther-no"]').click()
            cy.get('[data-testid="children.1.fileJoint-yes"]').click()
            cy.get('[data-testid="children.1.fileJointConfirm-no"]').click()
            cy.get('[data-testid="us50Percent-yes"]').click()
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="resultsIntro-p1"]').contains('$1')
        })
    })
    it('Scenario 9 - Joe QW', () => {
        cy.get('@contentJSON').then((content) => {
            cy.get('[data-testid="year-2021"]').click()
            cy.get('[data-testid="citizen-yes"]').click()
            cy.get('[data-testid="validSSN-yes"]').click()
            cy.get('[data-testid="foreignIncome-no"]').click()
            cy.get('[data-testid="claimedAsDependent-no"]').click()
            cy.get('[data-testid="age-2021-24over"]').click()
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="fsKnown-no"]').click()
            cy.get('[data-testid="maritalStatus-widow"]').click()
            cy.get('[data-testid="spousesPassing-last2Years"]').click()
            cy.get('[data-testid="entitledJointReturnDeceased-yes"]').click()
            cy.get('[data-testid="houseUpkeep2-yes"]').click()
            cy.get('[data-testid="claimDependent1-no"]').click()
            cy.get('[data-testid="claimDependent2-yes"]').click()
            cy.get('[data-testid="numOfDependents-10"]').click() //5
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="earnedIncome.wagesFederalWithheld.checked"]').click()
            cy.get('[data-testid="wagesFederalWithheld0-input"]').type('50500').should('have.value', '$50,500')
            cy.get('[data-testid="scholarshipLabel"]').click()
            cy.get('[data-testid="scholarship0-input"]').type('10000').should('have.value', '$10,000')
            cy.get('[data-testid="iraLabel"]').click()
            cy.get('[data-testid="ira0-input"]').type('5075').should('have.value', '$5,075')
            cy.get('[data-testid="hsaLabel"]').click()
            cy.get('[data-testid="hsa0-input"]').type('5000').should('have.value', '$5,000')
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="children.0.live51Pct-yes"]').click()
            cy.get('[data-testid="children.0.claimOther-no"]').click()
            cy.get('[data-testid="children.0.fileJoint-yes"]').click()
            cy.get('[data-testid="children.0.fileJointConfirm-yes"]').click()
            cy.get('[data-testid="children.0.permanentlyDisabled-yes"]').click()
            cy.get('[data-testid="children.0.relationship-other"]').click()

            cy.get('[id="child2-trigger"]').click() 
            cy.get('[data-testid="children.1.live51Pct-yes"]').click()
            cy.get('[data-testid="children.1.claimOther-yes"]').click()
            cy.get('[data-testid="children.1.claimOtherConfirm-no"]').click()

            cy.get('[id="child3-trigger"]').click() 
            cy.get('[data-testid="children.2.live51Pct-yes"]').click()
            cy.get('[data-testid="children.2.claimOther-no"]').click()
            cy.get('[data-testid="children.2.fileJoint-no"]').click()
            cy.get('[data-testid="children.2.permanentlyDisabled-no"]').click()
            cy.get('[data-testid="children.2.relationship-qualifyingRelationship1"]').click()
            cy.get('[data-testid="children.2.age-age-Under18"]').click()
            cy.get('[data-testid="children.2.validSSN-yes"]').click()
            
            cy.get('[id="child4-trigger"]').click() 
            cy.get('[data-testid="children.3.live51Pct-yes"]').click()
            cy.get('[data-testid="children.3.claimOther-no"]').click()
            cy.get('[data-testid="children.3.fileJoint-no"]').click()
            cy.get('[data-testid="children.3.permanentlyDisabled-yes"]').click()
            cy.get('[data-testid="children.3.relationship-qualifyingRelationship1"]').click()
            cy.get('[data-testid="children.3.validSSN-yes"]').click()
            
            cy.get('[id="child5-trigger"]').click() 
            cy.get('[data-testid="children.4.live51Pct-yes"]').click()
            cy.get('[data-testid="children.4.claimOther-no"]').click()
            cy.get('[data-testid="children.4.fileJoint-no"]').click()
            cy.get('[data-testid="children.4.permanentlyDisabled-no"]').click()
            cy.get('[data-testid="children.4.relationship-qualifyingRelationship1"]').click()
            cy.get('[data-testid="children.4.age-age-19-23"]').click()
            cy.get('[data-testid="children.4.student-yes"]').click()
            cy.get('[data-testid="children.4.validSSN-yes"]').click()
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="resultsIntro-p1"]').contains('$199')
        })
    })
})