/* eslint-disable max-len */
describe('AGI Page', () => {
    it('Checkbox Verification', () => {
        cy.get('@contentJSON').then((content) => {
            cy.filingStatusPage()
            // Title and Info header
            cy.get('[data-testid="agiTitle"]').should('have.text', content.agi.title).and('be.visible')
            cy.get('[data-testid="agiParagraph1"]').should('have.text', content.agi.subTitle0).and('be.visible')
            cy.get('[data-testid="agiParagraph2"]').should('have.text', content.agi.subTitle1).and('be.visible')
            cy.get('[data-testid="reqText"]').should('have.text', content.reqText).and('be.visible')

            // MFJ Info Box
            cy.get('[data-testid="stepIndicatorStep2"]').click()
            cy.get('[data-testid="filingStatus-married"]').click()
            cy.get('[data-testid="spouseValidSSN-yes"]').click()
            cy.get('[data-testid="nextButton"]').click()

            // Switch back to Single
            cy.get('[data-testid="stepIndicatorStep2"]').click()
            cy.get('[data-testid="filingStatus-single"]').click()
            cy.get('[data-testid="nextButton"]').click()

            //Eaned Income
            cy.get('[for="earnedIncome"]').should('have.text', content.agi.earnedIncome).and('be.visible')
            cy.get('[data-testid="wagesFederalWithheld-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="wagesToolTipHeader1"]').should('have.text', content.toolTip.wagesWithheldToolTipHeader1).and('be.visible')
            cy.get('[data-testid="wagesToolTipParagraph1"]').should('have.text', content.toolTip.wagesWithheldToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="wagesToolTipParagraph2"]').should('have.text', content.toolTip.wagesWithheldToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="wagesToolTipParagraph3"]').should('have.text', content.toolTip.wagesWithheldToolTipParagraph3).and('be.visible')
            cy.get('[data-testid="wagesToolTipHeader2"]').should('have.text', content.toolTip.wagesWithheldToolTipHeader2).and('be.visible')
            cy.get('[data-testid="wagesToolTipParagraph4"]').should('have.text', content.toolTip.wagesWithheldToolTipParagraph4).and('be.visible')
            cy.get('[data-testid="wagesToolTipParagraph5"]').should('have.text', content.toolTip.wagesWithheldToolTipParagraph5).and('be.visible')
            cy.get('[data-testid="wagesToolTipHeader3"]').should('have.text', content.toolTip.wagesWithheldToolTipHeader3).and('be.visible')
            cy.get('[data-testid="wagesToolTipParagraph6"]').should('have.text', content.toolTip.wagesWithheldToolTipParagraph6).and('be.visible')
            cy.get('[data-testid="wagesFederalWithheld-helpTip"]').click()
            cy.get('[data-testid="wagesWithheldToolTipParagraph1"]').should('not.exist')
            cy.get('[data-testid="wagesFederalWithheldLabel"]').should('have.text', content.agi.wagesWithheld).and('be.visible').click()
            cy.get('[data-testid="wagesFederalWithheld0-input"]').should('have.attr', 'placeholder', content.agi.enterAmount).and('be.visible')
            cy.get('[data-testid="wagesFederalWithheld0-input"]').type('999999999').should('have.value', '$99,999,999').and('be.visible')
            cy.get('[data-testid="wagesFederalWithheld0-input"]').clear()
            cy.get('[data-testid="wagesFederalWithheld0-input"]').type('hi$,()220000').should('have.value', '$220,000')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$220,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            cy.get('[data-testid="addAnother-wagesFederalWithheld"]').should('have.text', content.agi.addAnother).and('be.visible').click()

            // DELETE BUTTON
            cy.get('[data-testid="deleteButton1"]').should('be.visible')
            cy.get('[data-testid="wagesFederalWithheld1-input"]').should('be.visible')
            cy.get('[data-testid="addAnother-wagesFederalWithheld"]').should('have.text', content.agi.addAnother).and('be.visible')
            cy.get('[data-testid="wagesFederalWithheld1-input"]').type('hi$,()20000.01').should('have.value', '$20,000.01')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$240,000`).and('be.visible')
            cy.get('[data-testid="deleteButton1"]').click()
            cy.get('[data-testid="wagesFederalWithheld1-input"]').should('not.exist')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$220,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            cy.get('[data-testid="addAnother-wagesFederalWithheld"]').should('have.text', content.agi.addAnother).and('be.visible').click()
            // WAGES WITHHELD #2
            cy.get('[data-testid="deleteButton1"]').should('be.visible')
            cy.get('[data-testid="wagesFederalWithheld1-input"]').should('have.attr', 'placeholder', content.agi.enterAmount).and('be.visible')
            cy.get('[data-testid="wagesFederalWithheld1-input"]').type('999999999').should('have.value', '$99,999,999').and('be.visible')
            cy.get('[data-testid="wagesFederalWithheld1-input"]').clear()
            cy.get('[data-testid="wagesFederalWithheld1-input"]').type('hi$,()20000').should('have.value', '$20,000')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$240,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            cy.get('[data-testid="addAnother-wagesFederalWithheld"]').should('have.text', content.agi.addAnother).and('be.visible').click()
            // WAGES WITHHELD #3
            cy.get('[data-testid="deleteButton2"]').should('be.visible')
            cy.get('[data-testid="wagesFederalWithheld2-input"]').should('have.attr', 'placeholder', content.agi.enterAmount).and('be.visible')
            cy.get('[data-testid="wagesFederalWithheld2-input"]').type('999999999').should('have.value', '$99,999,999').and('be.visible')
            cy.get('[data-testid="wagesFederalWithheld2-input"]').clear()
            cy.get('[data-testid="wagesFederalWithheld2-input"]').type('hi$,()20000').should('have.value', '$20,000')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$260,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            cy.get('[data-testid="addAnother-wagesFederalWithheld"]').should('have.text', content.agi.addAnother).and('be.visible').click()
            // WAGES WITHHELD #4
            cy.get('[data-testid="deleteButton3"]').should('be.visible')
            cy.get('[data-testid="wagesFederalWithheld3-input"]').should('have.attr', 'placeholder', content.agi.enterAmount).and('be.visible')
            cy.get('[data-testid="wagesFederalWithheld3-input"]').type('999999999').should('have.value', '$99,999,999').and('be.visible')
            cy.get('[data-testid="wagesFederalWithheld3-input"]').clear()
            cy.get('[data-testid="wagesFederalWithheld3-input"]').type('hi$,()20000').should('have.value', '$20,000')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$280,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            cy.get('[data-testid="addAnother-wagesFederalWithheld"]').should('have.text', content.agi.addAnother).and('be.disabled')
            

            // TAX-DEFERRED RETIREMENT PLAN (LIKE A 401K)
            cy.get('[data-testid="taxDeferredRetirement-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="retirementToolTipHeader1"]').should('have.text', content.toolTip.deferredRetirementToolTipHeader).and('be.visible')
            cy.get('[data-testid="retirementToolTipParagraph1"]').should('have.text', content.toolTip.deferredRetirementToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="retirementToolTipList0"]').should('have.text', content.toolTip.deferredRetirementToolTipList0).and('be.visible')
            cy.get('[data-testid="retirementToolTipList1"]').should('have.text', content.toolTip.deferredRetirementToolTipList1).and('be.visible')
            cy.get('[data-testid="retirementToolTipList2"]').should('have.text', content.toolTip.deferredRetirementToolTipList2).and('be.visible')
            cy.get('[data-testid="retirementToolTipList3"]').should('have.text', content.toolTip.deferredRetirementToolTipList3).and('be.visible')
            cy.get('[data-testid="retirementToolTipList4"]').should('have.text', content.toolTip.deferredRetirementToolTipList4).and('be.visible')
            cy.get('[data-testid="retirementToolTipList5"]').should('have.text', content.toolTip.deferredRetirementToolTipList5).and('be.visible')
            cy.get('[data-testid="retirementToolTipList6"]').should('have.text', content.toolTip.deferredRetirementToolTipList6).and('be.visible')
            cy.get('[data-testid="taxDeferredRetirement-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="retirementToolTipParagraph1"]').should('be.not.visible')
            cy.get('[for="earnedIncome.wagesFederalWithheldNested"]').should('have.text', content.agi.payrollDeductions).and('be.visible')
            cy.get('[data-testid="taxDeferredRetirementLabel"]').should('have.text', content.agi.deferredRetirement).and('be.visible').click()
            cy.get('[data-testid="taxDeferredRetirement0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$260,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // CAFETERIA PLAN
            cy.get('[data-testid="cafeteria-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="cafeteriaToolTipHeader1"]').should('have.text', content.toolTip.cafeteriaToolTipHeader).and('be.visible')
            cy.get('[data-testid="cafeteriaToolTipParagraph1"]').should('have.text', content.toolTip.cafeteriaToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="cafeteriaToolTipParagraph2"]').should('have.text', content.toolTip.cafeteriaToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="cafeteriaToolTipList0"]').should('have.text', content.toolTip.cafeteriaToolTipList0).and('be.visible')
            cy.get('[data-testid="cafeteriaToolTipList1"]').should('have.text', content.toolTip.cafeteriaToolTipList1).and('be.visible')
            cy.get('[data-testid="cafeteriaToolTipList2"]').should('have.text', content.toolTip.cafeteriaToolTipList2).and('be.visible')
            cy.get('[data-testid="cafeteriaToolTipList3"]').should('have.text', content.toolTip.cafeteriaToolTipList3).and('be.visible')
            cy.get('[data-testid="cafeteriaToolTipList4"]').should('have.text', content.toolTip.cafeteriaToolTipList4).and('be.visible')
            cy.get('[data-testid="cafeteriaToolTipList5"]').should('have.text', content.toolTip.cafeteriaToolTipList5).and('be.visible')
            cy.get('[data-testid="cafeteriaToolTipList6"]').should('have.text', content.toolTip.cafeteriaToolTipList6).and('be.visible')
            cy.get('[data-testid="cafeteriaToolTipList7"]').should('have.text', content.toolTip.cafeteriaToolTipList7).and('be.visible')
            cy.get('[data-testid="cafeteriaToolTipList8"]').should('have.text', content.toolTip.cafeteriaToolTipList8).and('be.visible')
            cy.get('[data-testid="cafeteriaToolTipList9"]').should('have.text', content.toolTip.cafeteriaToolTipList9).and('be.visible')
            cy.get('[data-testid="cafeteria-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="cafeteriaToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="cafeteriaLabel"]').should('have.text', content.agi.cafeteria).and('be.visible').click()
            cy.get('[data-testid="cafeteria0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$240,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // HEALTH INSURNANCE PREMIUMS
            cy.get('[data-testid="healthInsurance-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="healthInsuranceToolTipHeader1"]').should('have.text', content.toolTip.healthInsurancePremiumsToolTipHeader).and('be.visible')
            cy.get('[data-testid="healthInsuranceToolTipParagraph1"]').should('have.text', content.toolTip.healthInsurancePremiumsToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="healthInsurance-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="healthInsuranceToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="healthInsuranceLabel"]').should('have.text', content.agi.healthInsurancePremiums).and('be.visible').click()
            cy.get('[data-testid="healthInsurance0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
             cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$220,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // FEDERAL INCOME NOT WITHHELD
            cy.get('[data-testid="federalIncomeNotWithheld-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="FINWToolTipHeader1"]').should('have.text', content.toolTip.incomeTaxesNotWithheldToolTipHeader).and('be.visible')
            cy.get('[data-testid="FINWToolTipParagraph1"]').should('have.text', content.toolTip.incomeTaxesNotWithheldToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="FINWToolTipList0"]').should('have.text', content.toolTip.incomeTaxesNotWithheldToolTipList0).and('be.visible')
            cy.get('[data-testid="FINWToolTipList1"]').should('have.text', content.toolTip.incomeTaxesNotWithheldToolTipList1).and('be.visible')
            cy.get('[data-testid="FINWToolTipList2"]').should('have.text', content.toolTip.incomeTaxesNotWithheldToolTipList2).and('be.visible')
            cy.get('[data-testid="FINWToolTipList3"]').should('have.text', content.toolTip.incomeTaxesNotWithheldToolTipList3).and('be.visible')
            cy.get('[data-testid="FINWToolTipList4"]').should('have.text', content.toolTip.incomeTaxesNotWithheldToolTipList4).and('be.visible')
            cy.get('[data-testid="FINWToolTipParagraph2"]').should('have.text', content.toolTip.incomeTaxesNotWithheldToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="FINWToolTipLink1"]').should('have.attr', 'href', content.toolTip.incomeTaxesNotWithheldToolTipLink1).and('be.visible')
            cy.get('[data-testid="federalIncomeNotWithheld-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="FINWToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="federalIncomeNotWithheldLabel"]').should('have.text', content.agi.incomeTaxesNotWithheld).and('be.visible').click()
            cy.get('[data-testid="federalIncomeNotWithheld-callout"]').should('have.text', content.agi.infoAlert).and('be.visible')
            cy.get('[data-testid="federalIncomeNotWithheld0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$240,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // SELF EMPLOYMENT ADJUSTMENTS
            cy.get('[data-testid="selfEmploymentPaidFINW-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="selfEmploymentPaidFINWHelpTipParagraph1"]').should('have.text', content.toolTip.selfEmploymentPaidToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="selfEmploymentPaidFINW-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="selfEmploymentPaidFINWHelpTipParagraph1"]').should('be.not.visible')
            cy.get('[for="earnedIncome.federalIncomeNotWithheldNested"]').should('have.text', content.agi.selfEmploymentAdjustments).and('be.visible')
            cy.get('[data-testid="selfEmploymentPaidFINWLabel"]').should('have.text', content.agi.selfEmploymentPaid).and('be.visible').click()
            cy.get('[data-testid="selfEmploymentPaidFINW0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$220,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
                    
            // FINW SIMPLE
            cy.get('[data-testid="sepSimpleFINW-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="sepSimpleFINWToolTipHeader1"]').should('have.text', content.toolTip.sepSimpleToolTipHeader).and('be.visible')
            cy.get('[data-testid="sepSimpleFINWToolTipParagraph1"]').should('have.text', content.toolTip.sepSimpleToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="sepSimpleFINWToolTipList0"]').should('have.text', content.toolTip.sepSimpleToolTipList0).and('be.visible')
            cy.get('[data-testid="sepSimpleFINWToolTipList1"]').should('have.text', content.toolTip.sepSimpleToolTipList1).and('be.visible')
            cy.get('[data-testid="sepSimpleFINWToolTipParagraph2"]').should('have.text', content.toolTip.sepSimpleToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="sepSimpleFINWToolTipLink1"]').should('have.attr', 'href', content.toolTip.sepSimpleToolTipLink1).and('be.visible')
            cy.get('[data-testid="sepSimpleFINW-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="sepSimpleFINWToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="sepSimpleFINWLabel"]').should('have.text', content.agi.sepSimple).and('be.visible').click()
            cy.get('[data-testid="sepSimpleFINW0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$200,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // FINW HEALTH INSURANCE
            cy.get('[data-testid="selfEmploymentInsuranceFINW-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="selfEmploymentInsuranceFINWToolTipHeader1"]').should('have.text', content.toolTip.selfEmploymentInsuranceToolTipHeader).and('be.visible')
            cy.get('[data-testid="selfEmploymentInsuranceFINWToolTipParagraph1"]').should('have.text', content.toolTip.selfEmploymentInsuranceToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="selfEmploymentInsuranceFINWToolTipParagraph2"]').should('have.text', content.toolTip.selfEmploymentInsuranceToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="selfEmploymentInsuranceFINWToolTipLink1"]').should('have.attr', 'href', content.toolTip.selfEmploymentInsuranceToolTipLink1).and('be.visible')
            cy.get('[data-testid="selfEmploymentInsuranceFINW-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="selfEmploymentInsuranceFINWToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="selfEmploymentInsuranceFINWLabel"]').should('have.text', content.agi.selfEmploymentInsurance).and('be.visible').click()
            cy.get('[data-testid="selfEmploymentInsuranceFINW0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$180,000`).and('be.visible')
           
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // FINW EXPENSES
            cy.get('[data-testid="selfEmploymentExpensesFINW-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="selfEmploymentExpensesFINWToolTipHeader1"]').should('have.text', content.toolTip.selfEmploymentExpensesToolTipHeader).and('be.visible')
            cy.get('[data-testid="selfEmploymentExpensesFINWToolTipParagraph1"]').should('have.text', content.toolTip.selfEmploymentExpensesToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="selfEmploymentExpensesFINW-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="selfEmploymentExpensesFINWToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="selfEmploymentExpensesFINWLabel"]').should('have.text', content.agi.selfEmploymentExpenses).and('be.visible').click()
            cy.get('[data-testid="selfEmploymentExpensesFINW0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$160,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // SE GROSS INCOME
            cy.get('[data-testid="selfEmploymentGross-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="selfEmploymentGrossToolTipHeader1"]').should('have.text', content.toolTip.selfEmploymentGrossToolTipHeader).and('be.visible')
            cy.get('[data-testid="selfEmploymentGrossToolTipParagraph1"]').should('have.text', content.toolTip.selfEmploymentGrossToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="selfEmploymentGrossToolTipList0"]').should('have.text', content.toolTip.selfEmploymentGrossToolTipList0).and('be.visible')
            cy.get('[data-testid="selfEmploymentGrossToolTipList1"]').should('have.text', content.toolTip.selfEmploymentGrossToolTipList1).and('be.visible')
            cy.get('[data-testid="selfEmploymentGrossToolTipList2"]').should('have.text', content.toolTip.selfEmploymentGrossToolTipList2).and('be.visible')
            cy.get('[data-testid="selfEmploymentGrossToolTipList3"]').should('have.text', content.toolTip.selfEmploymentGrossToolTipList3).and('be.visible')
            cy.get('[data-testid="selfEmploymentGrossToolTipParagraph2"]').should('have.text', content.toolTip.selfEmploymentGrossToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="selfEmploymentGrossToolTipParagraph3"]').should('have.text', content.toolTip.selfEmploymentGrossToolTipParagraph3).and('be.visible')
            cy.get('[data-testid="selfEmploymentGrossToolTipLink1"]').should('have.attr', 'href', content.toolTip.selfEmploymentGrossToolTipLink1).and('be.visible')
            cy.get('[data-testid="selfEmploymentGross-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="selfEmploymentGrossToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="selfEmploymentGrossLabel"]').should('have.text', content.agi.selfEmploymentGross).and('be.visible').click()
            cy.get('[data-testid="selfEmploymentGross-callout"]').should('have.text', content.agi.infoAlert).and('be.visible')
            cy.get('[data-testid="selfEmploymentGross0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$180,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // SE TAXES PAID
            cy.get('[data-testid="selfEmploymentPaidSEG-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="selfEmploymentPaidSEGToolTipParagraph1"]').should('have.text', content.toolTip.selfEmploymentPaidToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="selfEmploymentPaidSEG-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="selfEmploymentPaidSEGToolTipParagraph1"]').should('be.not.visible')
            cy.get('[for="earnedIncome.selfEmploymentGrossNested"]').should('have.text', content.agi.selfEmploymentAdjustments).and('be.visible')
            cy.get('[data-testid="selfEmploymentPaidSEGLabel"]').should('have.text', content.agi.selfEmploymentPaid).and('be.visible').click()
            cy.get('[data-testid="selfEmploymentPaidSEG0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$160,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // SE SIMPLE
            cy.get('[data-testid="sepSimpleSEG-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="sepSimpleSEGToolTipHeader1"]').should('have.text', content.toolTip.sepSimpleToolTipHeader).and('be.visible')
            cy.get('[data-testid="sepSimpleSEGToolTipParagraph1"]').should('have.text', content.toolTip.sepSimpleToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="sepSimpleSEGToolTipList0"]').should('have.text', content.toolTip.sepSimpleToolTipList0).and('be.visible')
            cy.get('[data-testid="sepSimpleSEGToolTipList1"]').should('have.text', content.toolTip.sepSimpleToolTipList1).and('be.visible')
            cy.get('[data-testid="sepSimpleSEGToolTipParagraph2"]').should('have.text', content.toolTip.sepSimpleToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="sepSimpleSEGToolTipLink1"]').should('have.attr', 'href', content.toolTip.sepSimpleToolTipLink1).and('be.visible')
            cy.get('[data-testid="sepSimpleSEG-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="sepSimpleSEGToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="sepSimpleSEGLabel"]').should('have.text', content.agi.sepSimple).and('be.visible').click()
            cy.get('[data-testid="sepSimpleSEG0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$140,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // SE HEALTH INSURANCE
            cy.get('[data-testid="selfEmploymentInsuranceSEG-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="selfEmploymentInsuranceSEGToolTipHeader1"]').should('have.text', content.toolTip.selfEmploymentInsuranceToolTipHeader).and('be.visible')
            cy.get('[data-testid="selfEmploymentInsuranceSEGToolTipParagraph1"]').should('have.text', content.toolTip.selfEmploymentInsuranceToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="selfEmploymentInsuranceSEGToolTipParagraph2"]').should('have.text', content.toolTip.selfEmploymentInsuranceToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="selfEmploymentInsuranceSEGToolTipLink1"]').should('have.attr', 'href', content.toolTip.selfEmploymentInsuranceToolTipLink1).and('be.visible')
            cy.get('[data-testid="selfEmploymentInsuranceSEG-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="selfEmploymentInsuranceSEGToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="selfEmploymentInsuranceSEGLabel"]').should('have.text', content.agi.selfEmploymentInsurance).and('be.visible').click()
            cy.get('[data-testid="selfEmploymentInsuranceSEG0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$120,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // SE EXPENSES
            cy.get('[data-testid="selfEmploymentExpensesSEG-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="selfEmploymentExpensesSEGToolTipHeader1"]').should('have.text', content.toolTip.selfEmploymentExpensesToolTipHeader).and('be.visible')
            cy.get('[data-testid="selfEmploymentExpensesSEGToolTipParagraph1"]').should('have.text', content.toolTip.selfEmploymentExpensesToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="selfEmploymentExpensesSEG-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="selfEmploymentExpensesSEGToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="selfEmploymentExpensesSEGLabel"]').should('have.text', content.agi.selfEmploymentExpenses).and('be.visible').click()
            cy.get('[data-testid="selfEmploymentExpensesSEG0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$100,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // DISABILITY RETIRMENT
            cy.get('[data-testid="disabilityRetirement-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="disabilityRetirementToolTipHeader1"]').should('have.text', content.toolTip.retirementDisabilityToolTipHeader).and('be.visible')
            cy.get('[data-testid="disabilityRetirementToolTipParagraph1"]').should('have.text', content.toolTip.retirementDisabilityToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="disabilityRetirementToolTipParagraph2"]').should('have.text', content.toolTip.retirementDisabilityToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="disabilityRetirement-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="disabilityRetirementToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="disabilityRetirementLabel"]').should('have.text', content.agi.disabilityRetirement).and('be.visible').click()
            cy.get('[data-testid="disabilityRetirement0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$120,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // FOREIGN INCOME
            cy.get('[data-testid="foreignEarnedIncome-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="foreignEarnedIncomeToolTipHeader1"]').should('have.text', content.toolTip.foreignToolTipHeader1).and('be.visible')
            cy.get('[data-testid="foreignEarnedIncomeToolTipParagraph1"]').should('have.text', content.toolTip.foreignToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="foreignEarnedIncomeToolTipParagraph2"]').should('have.text', content.toolTip.foreignToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="foreignEarnedIncomeToolTipLink1"]').should('have.attr', 'href', content.toolTip.foreignToolTipLink).and('be.visible')
            cy.get('[data-testid="foreignEarnedIncomeToolTipHeader2"]').should('have.text', content.toolTip.foreignToolTipHeader2).and('be.visible')
            cy.get('[data-testid="foreignEarnedIncomeToolTipParagraph3"]').should('have.text', content.toolTip.foreignToolTipParagraph3).and('be.visible')
            cy.get('[data-testid="foreignEarnedIncome-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="foreignEarnedIncomeToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="foreignEarnedIncomeLabel"]').should('have.text', content.agi.foreignIncome).and('be.visible').click()
            cy.get('[data-testid="foreignEarnedIncome0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$140,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // PRISON INCOME
            cy.get('[data-testid="prisonIncome-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="prisonIncomeToolTipHeader1"]').should('have.text', content.toolTip.prisonToolTipHeader1).and('be.visible')
            cy.get('[data-testid="prisonIncomeToolTipParagraph1"]').should('have.text', content.toolTip.prisonToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="prisonIncomeToolTipParagraph2"]').should('have.text', content.toolTip.prisonToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="prisonIncomeToolTipLink1"]').should('have.attr', 'href', content.toolTip.prisonToolTipLink).and('be.visible')
            cy.get('[data-testid="prisonIncome-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="prisonIncomeToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="prisonIncomeLabel"]').should('have.text', content.agi.inmatePay).and('be.visible').click()
            cy.get('[data-testid="prisonIncome-callout"]').should('have.text', content.agi.prisonCallout).and('be.visible').click()
            cy.get('[data-testid="prisonIncome0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$160,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
                    
            // NONE OF THE ABOVE
            cy.get('[data-testid="noIncome"]').should('have.text', content.agi.noIncome).and('be.visible')
            cy.get('[data-testid="noIncome"] > span > span > input').should('be.disabled')

            // UNEARNED INCOME
            cy.get('[for="unearnedIncome"]').should('have.text', content.agi.unearnedIncome).and('be.visible')
            // PENSION
            cy.get('[data-testid="pension-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="pensionToolTipHeader1"]').should('have.text', content.toolTip.pensionToolTipHeader).and('be.visible')
            cy.get('[data-testid="pensionToolTipParagraph1"]').should('have.text', content.toolTip.pensionToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="pensionToolTipParagraph2"]').should('have.text', content.toolTip.pensionToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="pensionToolTipList0"]').should('have.text', content.toolTip.pensionToolTipList0).and('be.visible')
            cy.get('[data-testid="pensionToolTipList1"]').should('have.text', content.toolTip.pensionToolTipList1).and('be.visible')
            cy.get('[data-testid="pensionToolTipList2"]').should('have.text', content.toolTip.pensionToolTipList2).and('be.visible')
            cy.get('[data-testid="pensionToolTipParagraph3"]').should('have.text', content.toolTip.pensionToolTipParagraph3).and('be.visible')
            cy.get('[data-testid="pensionToolTipList20"]').should('have.text', content.toolTip.pensionToolTipList20).and('be.visible')
            cy.get('[data-testid="pensionToolTipParagraph4"]').should('have.text', content.toolTip.pensionToolTipParagraph4).and('be.visible')
            cy.get('[data-testid="pensionToolTipParagraph5"]').should('have.text', content.toolTip.pensionToolTipParagraph5).and('be.visible')
            cy.get('[data-testid="pensionToolTipLink1"]').should('have.attr', 'href', content.toolTip.pensionToolTipLink1).and('be.visible')
            cy.get('[data-testid="pension-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="pensionToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="pensionLabel"]').should('have.text', content.agi.pension).and('be.visible').click()
            cy.get('[data-testid="pension0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$180,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
                    
            // UNEMPLOYEMENT INSURANCE
            cy.get('[data-testid="unemploymentInsurance-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="unemploymentInsuranceToolTipHeader1"]').should('have.text', content.toolTip.unemploymentInsuranceToolTipHeader).and('be.visible')
            cy.get('[data-testid="unemploymentInsuranceToolTipParagraph1"]').should('have.text', content.toolTip.unemploymentInsuranceToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="unemploymentInsuranceToolTipParagraph2"]').should('have.text', content.toolTip.unemploymentInsuranceToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="unemploymentInsurance-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="unemploymentInsuranceToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="unemploymentInsuranceLabel"]').should('have.text', content.agi.unemploymentInsurance).and('be.visible').click()
            cy.get('[data-testid="unemploymentInsurance0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$200,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // SSI OR RAILROAD BENEFITS
            cy.get('[data-testid="socialSecurityRailroad-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="SSToolTipHeader1"]').should('have.text', content.toolTip.railroadToolTipHeader).and('be.visible')
            cy.get('[data-testid="SSToolTipParagraph1"]').should('have.text', content.toolTip.railroadToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="SSToolTipParagraph2"]').should('have.text', content.toolTip.railroadToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="SSToolTipLink1"]').should('have.attr', 'href', content.toolTip.railroadToolTipLink1).and('be.visible')
            cy.get('[data-testid="SSToolTipParagraph3"]').should('have.text', content.toolTip.railroadToolTipParagraph3).and('be.visible')
            cy.get('[data-testid="SSToolTipLink2"]').should('have.attr', 'href', content.toolTip.railroadToolTipLink2).and('be.visible')
            cy.get('[data-testid="SSToolTipLink3"]').should('have.attr', 'href', content.toolTip.railroadToolTipLink3).and('be.visible')
            cy.get('[data-testid="socialSecurityRailroad-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="SSToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="socialSecurityRailroadLabel"]').should('have.text', content.agi.railroad).and('be.visible').click()
            cy.get('[data-testid="socialSecurityRailroad0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$220,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // SCHOLARSHIP
            cy.get('[data-testid="scholarship-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="scholarshipToolTipHeader1"]').should('have.text', content.toolTip.grantToolTipHeader).and('be.visible')
            cy.get('[data-testid="scholarshipToolTipParagraph1"]').should('have.text', content.toolTip.grantToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="scholarshipToolTipList0"]').should('have.text', content.toolTip.grantToolTipList0).and('be.visible')
            cy.get('[data-testid="scholarshipToolTipList1"]').should('have.text', content.toolTip.grantToolTipList1).and('be.visible')
            cy.get('[data-testid="scholarshipToolTipParagraph2"]').should('have.text', content.toolTip.grantToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="scholarshipToolTipParagraph3"]').should('have.text', content.toolTip.grantToolTipParagraph3).and('be.visible')
            cy.get('[data-testid="scholarshipToolTipLink1"]').should('have.attr', 'href', content.toolTip.grantToolTipLink1).and('be.visible')
            cy.get('[data-testid="scholarship-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="scholarshipToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="scholarshipLabel"]').should('have.text', content.agi.grant).and('be.visible').click()
            cy.get('[data-testid="scholarship0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$240,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // INVESTMENT INCOME
            cy.get('[data-testid="investments-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="investmentsToolTipHeader1"]').should('have.text', content.toolTip.investmentIncomeToolTipHeader).and('be.visible')
            cy.get('[data-testid="investmentsToolTipParagraph1"]').should('have.text', content.toolTip.investmentIncomeToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="investmentsToolTipList0"]').should('have.text', content.toolTip.investmentIncomeToolTipList0).and('be.visible')
            cy.get('[data-testid="investmentsToolTipList1"]').should('have.text', content.toolTip.investmentIncomeToolTipList1).and('be.visible')
            cy.get('[data-testid="investmentsToolTipList2"]').should('have.text', content.toolTip.investmentIncomeToolTipList2).and('be.visible')
            cy.get('[data-testid="investmentsToolTipList3"]').should('have.text', content.toolTip.investmentIncomeToolTipList3).and('be.visible')
            cy.get('[data-testid="investmentsToolTipList4"]').should('have.text', content.toolTip.investmentIncomeToolTipList4).and('be.visible')
            cy.get('[data-testid="investmentsToolTipParagraph2"]').should('have.text', content.toolTip.investmentIncomeToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="investmentsToolTipLink1"]').should('have.attr', 'href', content.toolTip.investmentIncomeToolTipLink1).and('be.visible')
            cy.get('[data-testid="investmentsToolTipParagraph3"]').should('have.text', content.toolTip.investmentIncomeToolTipParagraph3).and('be.visible')
            cy.get('[data-testid="investmentsToolTipLink2"]').should('have.attr', 'href', content.toolTip.investmentIncomeToolTipLink2).and('be.visible')
            cy.get('[data-testid="investmentsToolTipList20"]').should('have.text', content.toolTip.investmentIncomeToolTipList00).and('be.visible')
            cy.get('[data-testid="investmentsToolTipList21"]').should('have.text', content.toolTip.investmentIncomeToolTipList10).and('be.visible')
            cy.get('[data-testid="investmentsToolTipList22"]').should('have.text', content.toolTip.investmentIncomeToolTipList20).and('be.visible')
            cy.get('[data-testid="investmentsToolTipList23"]').should('have.text', content.toolTip.investmentIncomeToolTipList30).and('be.visible')
            cy.get('[data-testid="investmentsToolTipList24"]').should('have.text', content.toolTip.investmentIncomeToolTipList40).and('be.visible')
            cy.get('[data-testid="investments-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="investmentsToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="investmentsLabel"]').should('have.text', content.agi.investmentIncome).and('be.visible').click()
            cy.get('[data-testid="investments0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$260,000`).and('be.visible')
            cy.get('[data-testid="investmentIncomeOverHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="investmentIncomeOver-p1"]').should('have.text', content.agi.investmentDQParagraph1).and('be.visible')
            cy.get('[data-testid="investmentIncomeOver-b1"]').should('have.text', content.agi.investmentDQParagraph2).and('be.visible')
            cy.get('[data-testid="investmentIncomeOver-ul10"]').should('have.text', content.agi.investmentDQList0).and('be.visible')
            cy.get('[data-testid="investmentIncomeOver-ul11"]').should('have.text', content.agi.investmentDQList1).and('be.visible')
            cy.get('[data-testid="investmentIncomeOver-ul12"]').should('have.text', content.agi.investmentDQList2).and('be.visible')
            cy.get('[data-testid="investmentIncomeOver-ul13"]').should('have.text', content.agi.investmentDQList3).and('be.visible')
            cy.get('[data-testid="investmentIncomeOver-ul14"]').should('have.text', content.agi.investmentDQList4).and('be.visible')
            cy.get('[data-testid="investmentIncomeOver-p2"]').should('have.text', content.agi.investmentDQParagraph3).and('be.visible')
            cy.get('[data-testid="investmentIncomeOver-p3"]').should('have.text', content.agi.investmentDQParagraph4).and('be.visible')
            cy.get('[data-testid="investmentIncomeOver-a1"]').should('have.attr', 'href', content.agi.investmentDQLink1).and('be.visible')
            cy.get('[data-testid="investmentIncomeOver-a2').should('have.attr', 'href', content.agi.investmentDQLink2).and('be.visible')
            
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // OTHER INCOME
            cy.get('[data-testid="unearnedOther-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="unearnedOtherToolTipHeader1"]').should('have.text', content.toolTip.otherUnearnedToolTipHeader).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipParagraph1"]').should('have.text', content.toolTip.otherUnearnedToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList0"]').should('have.text', content.toolTip.otherUnearnedToolTipList0).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList1"]').should('have.text', content.toolTip.otherUnearnedToolTipList1).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList2"]').should('have.text', content.toolTip.otherUnearnedToolTipList2).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList3"]').should('have.text', content.toolTip.otherUnearnedToolTipList3).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList4"]').should('have.text', content.toolTip.otherUnearnedToolTipList4).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList5"]').should('have.text', content.toolTip.otherUnearnedToolTipList5).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList6"]').should('have.text', content.toolTip.otherUnearnedToolTipList6).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList7"]').should('have.text', content.toolTip.otherUnearnedToolTipList7).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList8"]').should('have.text', content.toolTip.otherUnearnedToolTipList8).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList9"]').should('have.text', content.toolTip.otherUnearnedToolTipList9).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList10"]').should('have.text', content.toolTip.otherUnearnedToolTipList10).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList11"]').should('have.text', content.toolTip.otherUnearnedToolTipList11).and('be.visible')          
            cy.get('[data-testid="unearnedOtherToolTipParagraph2"]').should('have.text', content.toolTip.otherUnearnedToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList20"]').should('have.text', content.toolTip.otherUnearnedToolTipList20).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList21"]').should('have.text', content.toolTip.otherUnearnedToolTipList21).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList22"]').should('have.text', content.toolTip.otherUnearnedToolTipList22).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList23"]').should('have.text', content.toolTip.otherUnearnedToolTipList23).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList24"]').should('have.text', content.toolTip.otherUnearnedToolTipList24).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList25"]').should('have.text', content.toolTip.otherUnearnedToolTipList25).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList26"]').should('have.text', content.toolTip.otherUnearnedToolTipList26).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList27"]').should('have.text', content.toolTip.otherUnearnedToolTipList27).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList28"]').should('have.text', content.toolTip.otherUnearnedToolTipList28).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipList29"]').should('have.text', content.toolTip.otherUnearnedToolTipList29).and('be.visible')
            cy.get('[data-testid="unearnedOtherToolTipLink1"]').should('have.attr', 'href', content.toolTip.otherUnearnedToolTipLink1).and('be.visible')
            cy.get('[data-testid="unearnedOther-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="unearnedOtherToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="unearnedOtherLabel"]').should('have.text', content.agi.otherUnearned).and('be.visible').click()
            cy.get('[data-testid="unearnedOther0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$280,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // NONE OF THE ABOVE
            cy.get('[data-testid="noIncome"]').should('have.text', content.agi.noIncome).and('be.visible')
             cy.get('[data-testid="noUnEarnedIncome"] > span > span > input').should('be.disabled')

            // ADJUSTMENTS TO INCOME
            cy.get('[for="adjustments"]').should('have.text', content.agi.incomeAdjustments).and('be.visible')
            // STUDENT LOAN
            cy.get('[data-testid="studentLoan-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="studentLoanToolTipHeader1"]').should('have.text', content.toolTip.studentLoanToolTipHeader).and('be.visible')
            cy.get('[data-testid="studentLoanToolTipParagraph1"]').should('have.text', content.toolTip.studentLoanToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="studentLoanToolTipParagraph2"]').should('have.text', content.toolTip.studentLoanToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="studentLoanToolTipList0"]').should('have.text', content.toolTip.studentLoanToolTipList0).and('be.visible')
            cy.get('[data-testid="studentLoanToolTipList1"]').should('have.text', content.toolTip.studentLoanToolTipList1).and('be.visible')
            cy.get('[data-testid="studentLoanToolTipList2"]').should('have.text', content.toolTip.studentLoanToolTipList2).and('be.visible')
            cy.get('[data-testid="studentLoanToolTipParagraph3"]').should('have.text', content.toolTip.studentLoanToolTipParagraph3).and('be.visible')
            cy.get('[data-testid="studentLoanToolTipParagraph4"]').should('have.text', content.toolTip.studentLoanToolTipParagraph4).and('be.visible')
            cy.get('[data-testid="studentLoanToolTipLink1"]').should('have.attr', 'href', content.toolTip.studentLoanToolTipLink1).and('be.visible')
            cy.get('[data-testid="studentLoan-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="studentLoanToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="studentLoanLabel"]').should('have.text', content.agi.studentLoan).and('be.visible').click()
            cy.get('[data-testid="studentLoan0-input"]').type('2499')
            cy.get('[data-testid="studentLoan-callout"]').should('be.visible')
            cy.get('[data-testid="studentLoan0-input"]').clear().type('2500')
            cy.get('[data-testid="studentLoan-callout"]').should('have.text', content.agi.studentLoanCallout).and('be.visible').click()
            cy.get('[data-testid="studentLoan0-input"]').clear().type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$260,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // EDUCATOR EXPENSES
            cy.get('[data-testid="educator-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="educatorToolTipHeader1"]').should('have.text', content.toolTip.educatorToolTipHeader).and('be.visible')
            cy.get('[data-testid="educatorToolTipParagraph1"]').should('have.text', content.toolTip.educatorToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="educatorToolTipList0"]').should('have.text', content.toolTip.educatorToolTipList0).and('be.visible')
            cy.get('[data-testid="educatorToolTipList1"]').should('have.text', content.toolTip.educatorToolTipList1).and('be.visible')
            cy.get('[data-testid="educatorToolTipList2"]').should('have.text', content.toolTip.educatorToolTipList2).and('be.visible')
            cy.get('[data-testid="educatorToolTipList3"]').should('have.text', content.toolTip.educatorToolTipList3).and('be.visible')
            cy.get('[data-testid="educatorToolTipList4"]').should('have.text', content.toolTip.educatorToolTipList4).and('be.visible')
            cy.get('[data-testid="educatorToolTipParagraph2"]').should('have.text', content.toolTip.educatorToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="educatorToolTipLink1"]').should('have.attr', 'href', content.toolTip.educatorToolTipLink1).and('be.visible')
            cy.get('[data-testid="educator-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="educatorToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="educatorLabel"]').should('have.text', content.agi.educator).and('be.visible').click()
            cy.get('[data-testid="educator0-input"]').type('249')
            cy.get('[data-testid="educator-callout"]').should('be.visible')
            cy.get('[data-testid="educator0-input"]').clear().type('250')
            cy.get('[data-testid="educator-callout"]').should('have.text', content.agi.educatorCallout).and('be.visible').click()
            
            // Educator limit is different when taxpayer is MFJ
            cy.get('[data-testid="stepIndicatorStep2"]').click()
            cy.get('[data-testid="filingStatus-married"]').click()
            cy.get('[data-testid="spouseValidSSN-yes"]').click()
            cy.get('[data-testid="wasSpouseAliveEndOfYear-input-yes"]').click()
            cy.get('[data-testid="spouseAge-input-under24"]').click()
            cy.get('[data-testid="nextButton"]').click()

            cy.get('[data-testid="educator0-input"]').clear().type('499')
            cy.get('[data-testid="educator-callout"]').should('be.visible')
            cy.get('[data-testid="educator0-input"]').clear().type('500')
            cy.get('[data-testid="educator-callout"]').should('have.text', content.agi.educatorCalloutMFJ).and('be.visible').click()
            cy.get('[data-testid="educator0-input"]').clear().type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$240,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // IRA
            cy.get('[data-testid="ira-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="iraToolTipHeader1"]').should('have.text', content.toolTip.iraToolTipHeader).and('be.visible')
            cy.get('[data-testid="iraToolTipParagraph1"]').should('have.text', content.toolTip.iraToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="iraToolTipParagraph2"]').should('have.text', content.toolTip.iraToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="iraToolTipParagraph3"]').should('have.text', content.toolTip.iraToolTipParagraph3).and('be.visible')
            cy.get('[data-testid="iraToolTipLink1"]').should('have.attr', 'href', content.toolTip.iraToolTipLink1).and('be.visible')
            cy.get('[data-testid="ira-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="iraToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="iraLabel"]').should('have.text', content.agi.ira).and('be.visible').click()
            cy.get('[data-testid="ira0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$220,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // HSA
            cy.get('[data-testid="hsa-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="hsaToolTipHeader1"]').should('have.text', content.toolTip.hsaToolTipHeader).and('be.visible')
            cy.get('[data-testid="hsaToolTipParagraph1"]').should('have.text', content.toolTip.hsaToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="hsaToolTipParagraph2"]').should('have.text', content.toolTip.hsaToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="hsaToolTipLink1"]').should('have.attr', 'href', content.toolTip.hsaToolTipLink1).and('be.visible')
            cy.get('[data-testid="hsa-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="hsaToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="hsaLabel"]').should('have.text', content.agi.hsa).and('be.visible').click()
            cy.get('[data-testid="hsa0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$200,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // MOVING FOR MILITARY
            cy.get('[data-testid="moving-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="movingToolTipHeader1"]').should('have.text', content.toolTip.movingToolTipHeader).and('be.visible')
            cy.get('[data-testid="movingToolTipParagraph1"]').should('have.text', content.toolTip.movingToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="movingToolTipList0"]').should('have.text', content.toolTip.movingToolTipList0).and('be.visible')
            cy.get('[data-testid="movingToolTipList1"]').should('have.text', content.toolTip.movingToolTipList1).and('be.visible')
            cy.get('[data-testid="movingToolTipParagraph2"]').should('have.text', content.toolTip.movingToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="movingToolTipLink1"]').should('have.attr', 'href', content.toolTip.movingToolTipLink1).and('be.visible')
            cy.get('[data-testid="moving-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="movingToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="movingLabel"]').should('have.text', content.agi.moving).and('be.visible').click()
            cy.get('[data-testid="moving0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$180,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // ALIMONY PAID
            cy.get('[data-testid="alimony-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="alimonyToolTipHeader1"]').should('have.text', content.toolTip.alimonyToolTipHeader).and('be.visible')
            cy.get('[data-testid="alimonyToolTipParagraph1"]').should('have.text', content.toolTip.alimonyToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="alimonyToolTipParagraph2"]').should('have.text', content.toolTip.alimonyToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="alimonyToolTipList0"]').should('have.text', content.toolTip.alimonyToolTipList0).and('be.visible')
            cy.get('[data-testid="alimonyToolTipList1"]').should('have.text', content.toolTip.alimonyToolTipList1).and('be.visible')
            cy.get('[data-testid="alimonyToolTipParagraph3"]').should('have.text', content.toolTip.alimonyToolTipParagraph3).and('be.visible')
            cy.get('[data-testid="alimonyToolTipLink1"]').should('have.attr', 'href', content.toolTip.alimonyToolTipLink1).and('be.visible')
            cy.get('[data-testid="alimony-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="alimonyToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="alimonyLabel"]').should('have.text', content.agi.alimony).and('be.visible').click()
            cy.get('[data-testid="alimony0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$160,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // EARLY WITHDRAWAL FOR SAVINGS
            cy.get('[data-testid="earlyWithdrawalPenalty-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="earlyToolTipHeader1"]').should('have.text', content.toolTip.earlyWithdrawlPenaltyToolTipHeader).and('be.visible')
            cy.get('[data-testid="earlyToolTipParagraph1"]').should('have.text', content.toolTip.earlyWithdrawlPenaltyToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="earlyWithdrawalPenalty-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="earlyToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="earlyWithdrawalPenaltyLabel"]').should('have.text', content.agi.earlyWithdrawlPenalty).and('be.visible').click()
            cy.get('[data-testid="earlyWithdrawalPenalty0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$140,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // BUSINESS EXPENSES
            cy.get('[data-testid="business-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="businessToolTipHeader1"]').should('have.text', content.toolTip.businessToolTipHeader).and('be.visible')
            cy.get('[data-testid="businessToolTipParagraph1"]').should('have.text', content.toolTip.businessToolTipParagraph1).and('be.visible')
            cy.get('[data-testid="businessToolTipList0"]').should('have.text', content.toolTip.businessToolTipList0).and('be.visible')
            cy.get('[data-testid="businessToolTipList1"]').should('have.text', content.toolTip.businessToolTipList1).and('be.visible')
            cy.get('[data-testid="businessToolTipList2"]').should('have.text', content.toolTip.businessToolTipList2).and('be.visible')
            cy.get('[data-testid="businessToolTipList3"]').should('have.text', content.toolTip.businessToolTipList3).and('be.visible')
            cy.get('[data-testid="businessToolTipParagraph2"]').should('have.text', content.toolTip.businessToolTipParagraph2).and('be.visible')
            cy.get('[data-testid="businessToolTipParagraph3"]').should('have.text', content.toolTip.businessToolTipParagraph3).and('be.visible')
            cy.get('[data-testid="businessToolTipParagraph4"]').should('have.text', content.toolTip.businessToolTipParagraph4).and('be.visible')
            cy.get('[data-testid="businessToolTipLink1"]').should('have.attr', 'href', content.toolTip.businessToolTipLink1).and('be.visible')
            cy.get('[data-testid="business-helpTip"]').should('be.visible').click()
            cy.get('[data-testid="businessToolTipParagraph1"]').should('be.not.visible')
            cy.get('[data-testid="businessLabel"]').should('have.text', content.agi.business).and('be.visible').click()
            cy.get('[data-testid="business0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$120,000`).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarningHeading"]').should('have.text', content.agi.overEarnedIncomeLimitHeader).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p1"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph1).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-p2"]').should('have.text', content.agi.overEarnedIncomeLimitParagraph2).and('be.visible')
            cy.get('[data-testid="earnedIncomeLimitWarning-a1"]').should('have.attr', 'href', content.agi.overEarnedIncomeLimitLink).and('be.visible')
            
            // OTHER ADJUSTMENTS
            cy.get('[data-testid="otherAdjustmentsLabel"]').should('have.text', content.agi.otherAdjustments).and('be.visible').click()
            cy.get('[data-testid="otherAdjustments0-input"]').type('hi$,()20000').should('have.value', '$20,000').and('be.visible')
            cy.get('[data-testid="agiTotal"]').should('have.text', `${content.agi.totalAgi}$100,000`).and('be.visible')
            })
        })
        it('AGI page - ARPA', () => {
            cy.get('@contentJSON').then((content) => {
                cy.get('[data-testid="year-2021"]').click()
                cy.get('[data-testid="citizen-yes"]').click()
                cy.get('[data-testid="validSSN-yes"]').click()
                cy.get('[data-testid="foreignIncome-no"]').click()
                cy.get('[data-testid="claimedAsDependent-no"]').click()
                cy.get('[data-testid="age-2021-input-24over"]').click()
                cy.get('[data-testid="nextButton"]').click()
                cy.get('[data-testid="fsKnown-yes"]').click()
                cy.get('[data-testid="filingStatus-single"]').click()
                cy.get('[data-testid="numOfDependents-10"]').click()
                cy.get('[data-testid="nextButton"]').click()
                
                // Title and Info header
                cy.get('[data-testid="agiTitle"]').should('have.text', content.agi.title).and('be.visible')
                cy.get('[data-testid="agiParagraph1"]').should('be.visible')
                cy.get('[data-testid="agiParagraph2"]').should('be.visible')
                cy.get('[data-testid="reqText"]').should('have.text', content.reqText).and('be.visible')
        
                cy.get('[data-testid="agiARPAInfoAlertHeading"]').should('exist')
                cy.get('[data-testid="agiARPAInfoAlertParagraph"]').should('exist')
    
                // MFJ Info Box
                cy.get('[data-testid="stepIndicatorStep2"]').click()
                cy.get('[data-testid="filingStatus-married"]').click()
                cy.get('[data-testid="spouseValidSSN-yes"]').click()
                cy.get('[data-testid="nextButton"]').click()

                cy.get('[data-testid="agiARPAInfoAlertHeading"]').should('exist')
                cy.get('[data-testid="agiARPAInfoAlertParagraph"]').should('exist')
                cy.get('[data-testid="agiSpouseInfoAlertHeading"]').should('have.text', content.agi.agiSpouseInfoAlertHeading).and('be.visible')
                cy.get('[data-testid="agiSpouseInfoAlertParagraph"]').should('have.text', content.agi.agiSpouseInfoAlertParagraph).and('be.visible')
            })
        })
    })
